work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_iv_f0x4

model: model.vnn_multioutput_stgcn.UncertaintyAwareEarlyAttentionSTGCN
model_args:
    samples: 2
    attention_filter_limit: 0.1
    training_method: variational
    INIT_WEIGHTS: fill:stds:0.0001:0.0001

MODEL_NAME: uaeavstgcn

init_vnn_from: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/stgcn.best.pt

weights: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_iv_f0x4.best.pt
phase: test

include:
    - base
    - /vnn
