work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES
weights: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES.best.pt

# model
model: model.vnn_stgcn.VStgcn
model_args:
  samples: 2

MODEL_NAME: vstgcn

phase: test

include:
  - base
  - /vnn