work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks5_ts2

model: model.st3dgcnt.ST3DGCNT

MODEL_NAME: st3dgcnt

model_args:
    temporal_kernel_size: 5
    temporal_stride: 2
include:
    - base
