work_dir: ./work_dir/ntu_io2/xview/stgcn_joint
model_saved_name: ./runs/io2/ntu_cv_stgcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/train_data_joint.npy
  label_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/train_label.pkl
  class_filter_path: /home/io/har/skeleton-based-action-recognition/data/single_person_classes.txt
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/val_data_joint.npy
  label_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/val_label.pkl
  class_filter_path: /home/io/har/skeleton-based-action-recognition/data/single_person_classes.txt

# model
model: model.stgcn.STGCN
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 128
num_epoch: 50
nesterov: True
