work_dir: ./ood_runs/vnn/ntu60to120/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_slr

model: model.vnn_stgcn.VStgcn
model_args:
    samples: 2

MODEL_NAME: vstgcn

base_lr: 0.05
batch_size: 32

weights: ./runs/vnn/ntu60/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_slr.best.pt
phase: test

DATASET_NAME: ntu120
test_samples: [10]
test_batch_sizes: [512]
train_feeder_args:
    data_path: /data/sets/ntu3d/ntu120/xsub/train_data_joint.npy
    label_path: /data/sets/ntu3d/ntu120/xsub/train_label.pkl
    debug: False
    random_choose: False
    random_shift: False
    random_move: False
    window_size: -1
    normalization: False

test_feeder_args:
    data_path: /data/sets/ntu3d/ntu120/xsub/val_data_joint.npy
    label_path: /data/sets/ntu3d/ntu120/xsub/val_label.pkl
    debug: False

eval_loss: False
eval_var: True
save_for_ood: True

include:
    - base
    - /vnn
