work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks7_ts1

model: model.st3dgcnt.ST3DGCNT

MODEL_NAME: st3dgcnt

model_args:
    temporal_kernel_size: 7
    temporal_padding: 3
weights: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks7.best.pt
phase: test

include:
    - base
