# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /data/sets/ntu3d/ntu60/xsub/val_data_joint.npy
  label_path: /data/sets/ntu3d/ntu60/xsub/val_label.pkl
  debug: False

# model
model: model.vnn_stgcn.VStgcn
model_args:
  num_class: 120 # 60 for some times
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  samples: 10
  test_samples: 10


# test 
phase: test
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_2-49-29400.pt
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_3-49-14700.pt
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_5-79-47040.pt
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_5-79-47040.pt
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_init_xavier_uniform001_slr_3-29-17640.pt
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_init_xavier_uniform001_slr_2-29-17640.pt
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_init_xavier_uniform001_slr_4-29-17640.pt
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_init_xavier_uniform001_slr_6.latest.pt
# weights: ./runs/vntu/ntu_cv_vstgcn_joint_big_init_xavier_uniform001_slr_7.latest.pt
# weights: ./runs/vstgcn/xsub_vstgcn_ntu_60_joint-49-31300.pt
# weights: ./runs/ivstgcn/xsub_ivstgcn_ntu_60_joint_correct-29-18780.pt
weights: ./runs/ivstgcn/xsub_ivstgcn_ntu_60_joint_e50-49-31300.pt

work_dir: ./work_dir/ivstgcn/xsub/ivstgcn_ntu_60_joint_e50
model_saved_name: ./runs/vstgcn/xsub_ivstgcn_ntu_60_joint_e50
# work_dir: ./work_dir/vstgcn/xsub/ivstgcn_ntu_60_joint_correct
# model_saved_name: ./runs/vstgcn/xsub_ivstgcn_ntu_60_joint_correct
save_score: True
samples: [1,2,3,4,5,10,15,20,30,40]
device: [0,1,2,3,4,5,6,7]
test_batch_size: [512,512,512,512,512,256,256,128,128,128]
# device: [0,1]
# test_batch_size: [512,512,512,512,512,256,256,128,128,128]
device: [0,1]
test_batch_size: [512,512,512,512,512,256,256,128,128,128]
