work_dir: ./work_dir/vntu/xview/vstgcn_joint_big_init_xavier_uniform001_slr_3_
model_saved_name: ./runs/vntu/ntu_cv_vstgcn_joint_big_init_xavier_uniform001_slr_3_
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/train_data_joint.npy
  label_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/val_data_joint.npy
  label_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/val_label.pkl

# model
model: model.vnn_stgcn.VStgcn
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  samples: 1
  test_samples: 20
  INIT_WEIGHTS: "xavier_uniform0b:stds:0.01:0.01"

#optim
weight_decay: 0.0001
base_lr: 0.05
step: [10, 15, 20]

# training
device: [0, 1]
batch_size: 64
test_batch_size: 5
num_epoch: 30
nesterov: True
init_vnn_from: ./runs/stbln/ntu_cv_stgcn_joint-49-31350.pt
continue_global_step: False
