work_dir: ./work_dir/vntu/xview/vstgcn_joint_fix_2
model_saved_name: ./runs/vntu/ntu_cv_vstgcn_joint_fix_2
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/train_data_joint.npy
  label_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/val_data_joint.npy
  label_path: /home/io/har/pose_rotation/datasets/ntu3d/normalized/val_label.pkl

# model
model: model.vnn_stgcn.VStgcn
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  FIX_GAUSSIAN: 0.5

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1,2,3]
batch_size: 8
test_batch_size: 8
num_epoch: 50
nesterov: True
