work_dir: ./work_dir/vstgcn/xsub/vstgcn_ntu_60_joint
model_saved_name: ./runs/vstgcn/xsub_vstgcn_ntu_60_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data/sets/ntu3d/ntu60/xsub/train_data_joint.npy
  label_path: /data/sets/ntu3d/ntu60/xsub/train_label.pkl
  # class_filter_path: /home/io/har/skeleton-based-action-recognition/data/two_classes.txt
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data/sets/ntu3d/ntu60/xsub/val_data_joint.npy
  label_path: /data/sets/ntu3d/ntu60/xsub/val_label.pkl
  # class_filter_path: /home/io/har/skeleton-based-action-recognition/data/single_person_classes.txt

# model
model: model.vnn_stgcn.VStgcn
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  samples: 2
  test_samples: 20

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0, 1, 2, 3]
batch_size: 64
test_batch_size: 64
num_epoch: 50
nesterov: True
