work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks30_ts2

model: model.st3dgcnt.ST3DGCNT

MODEL_NAME: st3dgcnt

model_args:
    temporal_kernel_size: 30
    temporal_stride: 2
weights: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks30_ts2.best.pt
phase: test

include:
    - base
