work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks3_ts1

model: model.st3dgcnt.ST3DGCNT

MODEL_NAME: st3dgcnt

model_args:
    temporal_kernel_size: 3
    temporal_padding: 1
include:
    - base
