work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks30

model: model.st3dgcnt.ST3DGCNT

MODEL_NAME: st3dgcnt

model_args:
    temporal_kernel_size: 30
    temporal_stride: 3
include:
    - base
