work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE

model: model.vnn_multioutput_stgcn.UncertaintyAwareEarlyAttentionSTGCN
model_args:
    samples: 2
    attention_filter_limit: 0.7
    training_method: uncertainty_aware

MODEL_NAME: uaeavstgcn

weights: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE.best.pt
phase: test

include:
    - base
    - /vnn
