work_dir: ./work_dir/iuvagcn/kinetics/iuvagcn_kinetics_joint_iu2
model_saved_name: ./runs/iuvagcn/iuvagcn_kinetics_joint_iu2
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data/sets/kinetics/train_data_joint.npy
  label_path: /data/sets/kinetics/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data/sets/kinetics/val_data_joint.npy
  label_path: /data/sets/kinetics/val_label.pkl

# model
model: model.iu_vnn_agcn.IUVAGCN
model_name: agcn
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'
  samples: 1
  test_samples: 10
  iu_layers: [5, 10]

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [45, 55]

# training
device: [0,1,2,3]
batch_size: 32
test_batch_size: 32
num_epoch: 65
nesterov: True