work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks1_ts1

model: model.st3dgcn.ST3DGCN

MODEL_NAME: st3dgcn

model_args:
    temporal_kernel_size: 1
    temporal_padding: 0
weights: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks1.best.pt
phase: test

include:
    - base
