work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_iv

model: model.vnn_stgcn.VStgcn
model_args:
    samples: 4

MODEL_NAME: vstgcn

init_vnn_from: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/stgcn.best.pt

include:
    - base
    - /vnn
