work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks1_ts0

model: model.st3dgcnt.ST3DGCNT

MODEL_NAME: st3dgcnt

model_args:
    temporal_kernel_size: 1
    temporal_stride: 0
include:
    - base
