work_dir: ./work_dir/io_ntu/xview/agcn_joint_lwopenpose2d
model_saved_name: ./runs/io/ntu_cv_agcn_joint_lwopenpose2d
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/io/har/pose_rotation/datasets/ntu3d_opendpose/xview/train_data_joint.npy
  label_path: /home/io/har/pose_rotation/datasets/ntu3d_opendpose/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/io/har/pose_rotation/datasets/ntu3d_opendpose/xview/val_data_joint.npy
  label_path: /home/io/har/pose_rotation/datasets/ntu3d_opendpose/xview/val_label.pkl

# model
model: model.agcn.AGCN
model_name: agcn
model_args:
  num_class: 60
  num_point: 18
  num_person: 2
  in_channels: 2
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 128
num_epoch: 50
nesterov: True
