work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_iv_usual

model: model.vnn_agcn.VAGCN
model_args:
    samples: 1
    INIT_WEIGHTS: usual

MODEL_NAME: vagcn

init_vnn_from: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/agcn.best.pt

weights: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_iv_usual.best.pt
phase: test

include:
    - base
    - /vnn
