work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks15_ts2

model: model.a3dgcn.A3DGCN

MODEL_NAME: a3dgcn

model_args:
    temporal_kernel_size: 15
    temporal_stride: 2
weights: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks15_ts2.best.pt
phase: test

include:
    - base
