work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_iv_xu0b0x2_variational_trained_afl0.7

model: model.vnn_multioutput_stgcn.UncertaintyAwareEarlyAttentionSTGCN
model_args:
    samples: 8
    attention_filter_limit: 0.7
    training_method: variational
    INIT_WEIGHTS: xavier_uniform0b:stds:0.01:0.001

MODEL_NAME: uaeavstgcn

init_vnn_from: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/stgcn.best.pt

weights: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_iv_xu0b0x2_variational_trained.best.pt
phase: test

include:
    - base
    - /vnn
