work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_variational_trained_afl0.1

model: model.vnn_multioutput_stgcn.UncertaintyAwareEarlyAttentionSTGCN
model_args:
    samples: 8
    attention_filter_limit: 0.1
    training_method: variational

MODEL_NAME: uaeavstgcn

weights: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_s8_variational_trained.best.pt
phase: test

include:
    - base
    - /vnn
