work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_longer

model: model.vnn_stgcn.VStgcn
model_args:
    samples: 2

MODEL_NAME: vstgcn

include:
    - /kinetics/longer
    - base
    - /vnn
