work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks11_ts1

model: model.st3dgcn.ST3DGCN

MODEL_NAME: st3dgcn

model_args:
    temporal_kernel_size: 11
    temporal_padding: 5
include:
    - base
