work_dir: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL_tks100

model: model.st3dgcn.ST3DGCN

MODEL_NAME: st3dgcn

model_args:
    temporal_kernel_size: 100
    temporal_padding: 49
include:
    - base
