work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_bpb

model: model.vnn_agcn.VAGCN
model_args:
    samples: 2

MODEL_NAME: vagcn

batches_per_backpropagation: 4

weights: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_bpb.best.pt
phase: test

include:
    - base
    - /vnn
