work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES_b$BATCH_SIZE_iv_xn0b0x2

model: model.vnn_multioutput_agcn.UncertaintyAwareEarlyAttentionVAGCN
model_args:
    samples: 2
    training_method: uncertainty_aware
    INIT_WEIGHTS: xavier_uniform_0b:stds:0.01:0.001

MODEL_NAME: uaeavagcn

init_vnn_from: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/agcn.best.pt

include:
    - base
    - /vnn
