work_dir: ./runs/vnn/$DATASET/$SPLIT/$STREAMS/$MODEL_s$SAMPLES

# model
model: model.iu_vnn_agcn.IUVAGCN
model_args:
  samples: 2
  iu_layers: [4, 8]

MODEL_NAME: vagcn

include:
  - base
  - /vnn

base_lr: 0.05
step: [10, 15, 20]
init_vnn_from: ./runs/baselines/$DATASET/$SPLIT/$STREAMS/$MODEL.best.pt